# Generated by Django 3.2.8 on 2021-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credentials1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credentials2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profpic.jpg', upload_to='hood/'),
        ),
    ]
